CREATE TABLE IF NOT EXISTS usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100),
    tipo VARCHAR(100),
    endereco VARCHAR(100),
    cidade VARCHAR(100),
    preco DECIMAL(10,2),
    quartos INT,
    banheiros INT,
    area DECIMAL(10,2),
    descricao VARCHAR(500)
);

